name: Deploy React Application

on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4  
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t saad0saade008/react-app-selfrunner .  
      - name: Publish image to docker hub
        run: docker push saad0saade008/react-app-selfrunner
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from docker hub
        run: docker pull saad0saade008/react-app-selfrunner:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container 
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container saad0saade008/react-app-selfrunner
